= shtar(1)
Michael Ainsworth
v0.1
:doctype: manpage
:man-linkstyle: pass:[blue R < >]

== Name

shtar - an archive utility similar to `tar`

== Synopsis

*shtar* [_OPTION_]... 

== Options

*-h, --help*::
  Print a short help message.

*-i, --input* _FILE_::
  Use _FILE_ as the input. Note that _FILE_ can be a regular file, but it can
  also be a directory (e.g., for recursion). If _FILE_ is not specified,
  standard input is used and the resulting archive is not recursive - that is,
  it only contains a single file, not a directory with nested files and directories.

*-o, --output* _FILE_::
  Use _FILE_ as the output file name. If no output file is specified,
  standard ouput is used.

*-s, --shebang*::
  Include a "shebang" at the beginning of the output. Note that if this option
  is specified, the resulting output will include a _#!/bin/sh_ (or similar)
  line. See the _--sh-path_ option.

*-S, --no-shebang*::
  Do the _opposite_ of the _--shebang_ option.  That is, don't include the
  _#!/bin/sh_ line.

*-p, --sh-path* _PATH_::
  Indicate the path to the shell script interpreter. By default this is
  _#!/bin/sh_, although paths to other shells (like _#!/bin/dash_ and
  _#!/usr/local/bin/zsh_) should also fine too.

*-d, --destination* _FILE_::
  Use _FILE_ as the output path when extracting the archive. Note that this is
  not the same as the _--output_ option. That is, the _--output_ option will
  create a filesystem name _for the archive itself_ whereas the _--destination_
  option will create a filesystem name _for the extracted file or directory_.
  Note that for directories, the _--destination_ option is only used for the
  top-level directory.

== Exit status

`shtar` will exit with `0` on success and non `0` on failure. An error message
should appear indicating the cause of this error.

== Resources

`shtar` git repository on GitHub::
  https://github.com/nocloud-tech/shtar

== Copying

Copyright \(C) 2022 {author}.
Licensed under GPL-3.0-or-later.
See <https://www.gnu.org/licenses/>. 
